print("#############  ARRAY METHODS ##############")
array = ["Vansh","Rahi","Yash","Kaya","Shiv","Diya"]
print(array)
array.append("Ria")
print("append() : \n ",array)
print("---------------------------------------------------")
array.remove("Rahi")
print("remove() : \n ",array)
print("----------------------------------------------------")
array.sort()
print("sort() : \n ",array)
print("----------------------------------------------------")
array.clear()
print("clear() : \n ",array)
